info:
  contact: {}
paths:
  /:
    get:
      responses: {}
      summary: Hello
      x-perf-check:
        errorRate: 0.1
        latency: 100
  /group/a:
    post:
      responses: {}
      summary: TestRoute
      x-perf-check:
        errorRate: 0.05
        latency: 150
  /group/b:
    patch:
      responses: {}
      summary: TestRoute
      x-perf-check:
        errorRate: 0.1
        latency: 150
  /test-route:
    get:
      responses: {}
      summary: TestRoute
      x-perf-check:
        errorRate: 0.2
        latency: 250
swagger: "2.0"
