info:
  contact: {}
  title: Example API
paths:
  /:
    get:
      responses: {}
      summary: Hello
      x-perf-check:
        latency:
        - avg < 50
        - min < 50
schemes:
- http
swagger: "2.0"
x-perf-check:
  stages:
  - duration: 1s
    target: 5
